### ISSUE TITLE
TODO Website needs MLH Badge

### ISSUE THREAD

**Issue by ng-david** [bitcamp/bitcamp-site-2018#10]
Not sure which color or where to find at the moment (also haven't done any research on this part lol)

**Comment by timothychen01** [comment]
gimme a sec on this

**Comment by thisistimothychen** [comment]
https://mlh.io/brand-guidelines#trust-badge

**Comment by ng-david** [comment]
You're a hero

**Comment by thisistimothychen** [comment]
https://github.com/bitcamp/bitcamp-site-2018/pull/19
