### ISSUE TITLE
INVESTIGATE social media icon 

### ISSUE THREAD

**Issue by ng-david** [bitcamp/bitcamp-site-2018#13]
Should we use these icons. The palette and pixel count don't match the rest of the website

![image](https://user-images.githubusercontent.com/18043276/35786402-fa1b10ce-09f4-11e8-8676-f6762e982b5c.png)

**Comment by thisistimothychen** [comment]
i'm thinking the old ones might fit better

**Comment by ng-david** [comment]
Agreed, although I feel bad because Hanna just made these lol.

I'll run it by #design eventually

**Comment by thisistimothychen** [comment]
true...maybe just changing the color but keeping the pixel-y design so it's both Bitcamppy in style and color?

**Comment by thisistimothychen** [comment]
actually nvm then you wouldn't really be able to tell lol

**Comment by ng-david** [comment]
sadness
