### ISSUE TITLE
TODO trail markings to get smaller if you zoom out

### ISSUE THREAD

**Issue by thisistimothychen** [bitcamp/bitcamp-site-2018#15]
![image](https://user-images.githubusercontent.com/14797288/35787927-c0fc4f28-09ff-11e8-87a4-c21789ccf669.png)

**Comment by ng-david** [comment]
yeah probably, this'll be low priority for now though haha :)

**Comment by ng-david** [comment]
fixed on bded0e0cbe0a5999a97d508bc285d2f1d4f81a1e
