### ISSUE TITLE
TODO Make mobile navigation happen

### ISSUE THREAD

**Issue by ng-david** [bitcamp/bitcamp-site-2018#18]
`2-5-2018` -- EDIT: Ignore the hamburger menu icon, just use the text 'MENU' as it is on the latest master build.

I dont think I have time for this one. 

Please find someone to implement this if possible @wyapa or @timothychen01 

Basically the nav links get replaced by a single one, whose contents are a hamburger menu icon. Tapping on this brings open the top navigation of links, which pushes the whole web page down.

<img width="402" alt="screen shot 2018-02-05 at 12 25 26 am" src="https://user-images.githubusercontent.com/18043276/35789671-b33afdc4-0a0b-11e8-9e47-9fc5d9b9fac2.png">
<img width="402" alt="3" src="https://user-images.githubusercontent.com/18043276/35789672-b4a51abe-0a0b-11e8-986e-e4ffb5cafc54.png">

**Comment by thisistimothychen** [comment]
if we can't get to this one, i suggest we just have no nav on mobile?

**Comment by ng-david** [comment]
yeah that works, feasible until /colorwar goes active at least

but its okay, i can hack up an ugly mobile nav if all goes wrong too XD

**Comment by ng-david** [comment]
wokring on this
