### ISSUE TITLE
TODO Improve the trail path on the website 

### ISSUE THREAD

**Issue by ng-david** [bitcamp/bitcamp-site-2018#26]
Not sure if this is feasible to be done by Thursday. This task is up for grabs by anyone. 

Links:
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths
https://css-tricks.com/almanac/properties/s/stroke-dasharray/
http://thenewcode.com/744/Make-SVG-Responsive
See Noa's suggestions for this below:
![image](https://user-images.githubusercontent.com/18043276/35839457-84823d7c-0abe-11e8-8be0-5d6ca254f012.png)
![image](https://user-images.githubusercontent.com/18043276/35839501-bacfe69a-0abe-11e8-83b7-a34e8e7d2a4b.png)

**Comment by thisistimothychen** [comment]
Current: 
![image](https://user-images.githubusercontent.com/14797288/35960290-1d9e135a-0c77-11e8-98f1-825334ccef99.png)

Maybe?
![image](https://user-images.githubusercontent.com/14797288/35960276-120351fe-0c77-11e8-916a-767880a7727a.png)


I just played around with the CSS in dev console a bit -- could we just use a media query in the CSS for each trail?

**Comment by ng-david** [comment]
Yes sir, that's the solution to mobile.

Noa wants the paths to look better overall. I say first we make better mobile paths (like 3 lines of code) --- then we make the svg pathing

**Comment by thisistimothychen** [comment]
agreed! do you know where to put the lines, or do you want me to help look around?

**Comment by thisistimothychen** [comment]
done with above^

**Comment by ng-david** [comment]
@timothychen01 @person1123 I think we should make sure these new svg trails look good on mobile before pushing this live
