### ISSUE TITLE
TODO Content is missing from mostt of the website

### ISSUE THREAD

**Issue by ng-david** [bitcamp/bitcamp-site-2018#8]
Will be available here:
https://docs.google.com/document/d/1kr_f8bu7rpi3-Mg_GKeKP3Wxdeyo8y-4CYrTOMtDYUs/edit 

![image](https://user-images.githubusercontent.com/18043276/35899565-19d62a64-0b9b-11e8-9798-e10e5b8c7a24.png)

**Comment by thisistimothychen** [comment]
All content is up-to-date, just need to remove the schedule! :)

**Comment by thisistimothychen** [comment]
(Victoria will be getting me an updated volunteer/mentor link for the FAQ, but the current one will still work fine - just Google Forms vs Typeform, either way we'll get the info)

**Comment by ng-david** [comment]
will remove the schedule asap!
